#! /bin/python

import time

start_time = time.localtime()
print("Timer started at %s." % time.strftime("%X", start_time))

#Wait for user input
raw_input("Please press Enter key to continue...")

stop_time = time.localtime()
difference = time.mktime(stop_time) - time.mktime(start_time)

print("Timer stopped at %s." %time.strftime("%X", stop_time))
print("Your total time was %s." % difference)
